# Generated by Django 2.2 on 2023-01-18 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_marco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('dependencias', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('id_marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_marco.Marco')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tarefas a serem realizadas',
            },
        ),
    ]
