# Generated by Django 4.2 on 2024-06-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_marco', '0002_initial'),
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('goals', models.TextField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('dependencies', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tarefas')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id_marco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_marco.followup')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_of_the_task', to='app_project.project')),
            ],
            options={
                'verbose_name_plural': 'Tarefas a serem realizadas',
            },
        ),
    ]
