# Generated by Django 2.2 on 2023-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='custo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
