# Generated by Django 2.2 on 2023-01-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_projeto_status'),
        ('app_tarefas', '0003_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='id_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_of_the_task', to='app_project.Projeto'),
        ),
    ]
