# Generated by Django 2.2 on 2023-01-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tarefas', '0004_tarefa_id_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='id_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_of_the_task', to='app_project.Projeto'),
            preserve_default=False,
        ),
    ]
