# Generated by Django 4.2 on 2024-06-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('adm', 'adm'), ('cli', 'cli')], max_length=255, null=True),
        ),
    ]
