# Generated by Django 2.2 on 2023-01-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_user_user_pic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
