# Generated by Django 2.2 on 2023-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20230117_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic_profile',
            field=models.ImageField(default=1, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
