# Generated by Django 2.2 on 2023-01-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_funcoes', '0001_initial'),
        ('app_user', '0005_auto_20230117_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='function_in_the_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_funcoes.Funcao'),
        ),
    ]
