# Generated by Django 2.2 on 2023-04-20 16:50

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_user_function_in_the_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_pic_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles', validators=[validators.validate_file_size]),
        ),
    ]
