# Generated by Django 2.2 on 2023-01-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
        ('app_marco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marco',
            name='id_projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='app_project.Projeto'),
            preserve_default=False,
        ),
    ]
