# Generated by Django 4.2 on 2024-06-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_marco', '0001_initial'),
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='id_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='app_project.project'),
        ),
    ]
