# Generated by Django 2.2 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_status', '0001_initial'),
        ('app_marco', '0003_marco_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marco',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state_marco', to='app_status.Status'),
            preserve_default=False,
        ),
    ]
