# Generated by Django 2.2 on 2023-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marco', '0004_marco_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marco',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tarefas'),
        ),
    ]
