# Generated by Django 4.2 on 2024-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('gols', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tarefas')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('field', models.ManyToManyField(related_name='field', to='app_areas.field')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
