# Generated by Django 2.2 on 2023-01-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas', '0001_initial'),
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='app_areas.Area'),
            preserve_default=False,
        ),
    ]
