# Generated by Django 2.2 on 2023-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_projeto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='custo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
