# Generated by Django 2.2 on 2023-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_projeto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tarefas'),
        ),
    ]
