# Generated by Django 2.2 on 2023-01-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_areas', '0001_initial'),
        ('app_project', '0005_projeto_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='area',
        ),
        migrations.AddField(
            model_name='projeto',
            name='area',
            field=models.ManyToManyField(related_name='field', to='app_areas.Area'),
        ),
    ]
